CREATE TABLE employee_information (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    district VARCHAR(255),
    pincode BIGINT,
    departments VARCHAR(255),
    phone_number VARCHAR(10),
    salary NUMERIC,
    email_id VARCHAR(255) UNIQUE,
    age INT,
    total_years_of_experience INT,
    father_name VARCHAR(255),
    mother_name VARCHAR(255),
    previous_company VARCHAR(255),
    date_of_birth DATE,
    gender VARCHAR(50),
    marital_status VARCHAR(50),
    hire_date DATE,
    job_title VARCHAR(255),
    job_level VARCHAR(50),
    nationality VARCHAR(255),
    emergency_contact_name VARCHAR(255),
    emergency_contact_phone VARCHAR(10),
    employee_type VARCHAR(50),
    office_location VARCHAR(255),
    manager_name VARCHAR(255),
    medical_conditions VARCHAR(255),
    blood_group VARCHAR(10),
    languages_known VARCHAR(255),
    skills VARCHAR(255),
    educational_qualifications VARCHAR(255),
    certifications VARCHAR(255),
    joining_bonus NUMERIC,
    current_projects VARCHAR(255),
    performance_rating VARCHAR(50)
);
